language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep_history: true
  fqdn: edit.anli5005.rocks
  on:
    branch: master
